# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreationEtExport
                                 A QGIS plugin
 Ce plugin permet de créer un projet QGIS pré-configuré et d'exporter des illustrations automatiquement.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-06
        copyright            : (C) 2020 by Mathilde
        email                : mathilde.segaud@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreationEtExport class from file CreationEtExport.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .creation_export import CreationEtExport
    return CreationEtExport(iface)
