# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CreationExportV2
                                 A QGIS plugin
 Ce plugin créé un projet QGIS et exporte des illustrations automatiquement à partir de fichiers de configuration
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-07-17
        copyright            : (C) 2020 by Mathilde S
        email                : mathilde.segaud@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CreationExportV2 class from file CreationExportV2.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .creation_export_v2 import CreationExportV2
    return CreationExportV2(iface)
