# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LoadingProject
                                 A QGIS plugin
 This plugin load a project and load new layers into it
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-06-09
        copyright            : (C) 2020 by Me
        email                : mathilde.segaud@ensg.eu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LoadingProject class from file LoadingProject.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .load_project import LoadingProject
    return LoadingProject(iface)
